# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', '좋아요'), ('comment', '댓글'), ('ai_analysis', 'AI분석'), ('friend_request', '친구요청'), ('stock_movement', '주가변동'), ('product_recommendation', '상품추천')], max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('target_route', models.CharField(blank=True, max_length=80)),
                ('target_params', models.JSONField(blank=True, default=dict)),
                ('target_query', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=160)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notification_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'dedupe_key'], name='notification_user_dedupe_idx'),
        ),
    ]
