# Generated by Django 5.2.15 on 2026-06-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('category_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_summary', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('fallback', '대체 분석')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='analysis.monthlyanalysis')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyanalysis',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='monthly_analysis_unique_user_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlyanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_analysis_valid_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='monthly_analysis_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aianalysis',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['success', 'failed', 'fallback'])), name='ai_analysis_valid_status'),
        ),
    ]
