# Generated by Django 5.2.15 on 2026-06-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('finance', '0002_remove_productrecommendation_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
    ]
