# Generated by Django 5.2.15 on 2026-06-16 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_delete_aianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('log_count', models.PositiveIntegerField(default=0)),
                ('average_amount', models.PositiveBigIntegerField(default=0)),
                ('category_summary', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('saving_tip', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='analysis_mo_user_id_5aeffe_idx'), models.Index(fields=['user', 'year', 'month'], name='analysis_mo_user_id_c23fd7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_ai_analysis_valid_month'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='monthly_ai_analysis_total_nonnegative'), models.CheckConstraint(condition=models.Q(('log_count__gte', 0)), name='monthly_ai_analysis_log_count_nonnegative'), models.CheckConstraint(condition=models.Q(('average_amount__gte', 0)), name='monthly_ai_analysis_average_nonnegative'), models.CheckConstraint(condition=models.Q(('risk_level__in', ['low', 'medium', 'high'])), name='monthly_ai_analysis_valid_risk_level')],
            },
        ),
    ]
