# Generated by Django 5.2.15 on 2026-06-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('deposit', '예금'), ('saving', '적금')], max_length=10)),
                ('base_rate', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('max_rate', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('save_term', models.PositiveSmallIntegerField(help_text='가입 기간(개월)')),
                ('join_way', models.TextField(blank=True)),
                ('special_condition', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('bank_name', 'product_name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('product_type__in', ['deposit', 'saving'])), name='financial_product_valid_type'), models.CheckConstraint(condition=models.Q(('base_rate__gte', 0)), name='financial_product_base_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('max_rate__gte', 0)), name='financial_product_max_rate_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='analysis.aianalysis')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='finance.financialproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('priority', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('user', 'ai_analysis', 'product'), name='product_recommendation_unique_result'), models.CheckConstraint(condition=models.Q(('priority__gt', 0)), name='product_recommendation_priority_positive')],
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('stock_symbol',),
                'constraints': [models.UniqueConstraint(fields=('user', 'stock_symbol'), name='stock_holding_unique_user_symbol'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_holding_quantity_positive'), models.CheckConstraint(condition=models.Q(('average_price__gt', 0)), name='stock_holding_average_price_positive')],
            },
        ),
    ]
