# Generated by Django 5.2.15 on 2026-06-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRecommendation',
        ),
        migrations.DeleteModel(
            name='FinancialProduct',
        ),
        migrations.DeleteModel(
            name='StockHolding',
        ),
    ]
