# Generated by Django 5.2.15 on 2026-06-19 15:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_finlife_products_and_recommendations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('symbol',),
                'indexes': [models.Index(fields=['user', 'symbol'], name='stock_holding_user_symbol_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'symbol'), name='stock_holding_unique_user_symbol'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_holding_quantity_positive'), models.CheckConstraint(condition=models.Q(('average_price__gte', 0)), name='stock_holding_average_price_nonnegative'), models.CheckConstraint(condition=models.Q(('current_price__gte', 0)), name='stock_holding_current_price_nonnegative')],
            },
        ),
    ]
