# Generated by Django 5.2.15 on 2026-06-19 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_seed_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expenselog',
            name='expenses_ex_is_visi_6bc24e_idx',
        ),
        migrations.AddField(
            model_name='expenselog',
            name='hide_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='merchant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='overlay_style',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='overlay_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='visibility',
            field=models.CharField(choices=[('public', '전체 공개'), ('friends', '친구 공개'), ('private', '나만 보기')], default='friends', max_length=10),
        ),
        migrations.AddIndex(
            model_name='expenselog',
            index=models.Index(fields=['visibility', 'is_visible', '-created_at'], name='expenses_ex_visibil_c0a46e_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenselog',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'friends', 'private'])), name='expense_log_valid_visibility'),
        ),
    ]
