# Generated by Django 5.2.15 on 2026-06-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('accepted', '수락'), ('rejected', '거절')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='friend_prevent_self_request'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected'])), name='friend_valid_status'), models.UniqueConstraint(fields=('user', 'friend'), name='friend_unique_request_pair')],
            },
        ),
    ]
